[package]
name = "foray_data_model"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more.workspace = true
ndarray.workspace = true
relative-path.workspace = true
serde.workspace = true
pyo3.workspace = true
numpy.workspace = true
