[package]
name = "foray_graph"
version = "0.1.0"
edition = "2024"

[dependencies]
data_model = { path = "../data_model/" }
itertools.workspace = true
serde.workspace = true
log.workspace = true
ron.workspace = true
