[package]
name = "foray_py"
version = "0.1.0"
edition = "2024"

[dependencies]
foray_data_model = { path = "../foray_data_model/" }
pyo3.workspace = true
numpy.workspace = true
serde.workspace = true
relative-path.workspace = true
log.workspace = true
